/**
 * Offline directory snapshot
 * ==========================
 *
 * The frontend ships a static copy of the real OpenStreetMap directory
 * (`public/data/listings.json`, regenerated by `npm run sync:directory`).
 *
 * It is used **only** when the API cannot be reached. That is a common state:
 * the app is often deployed as a static bundle (Vercel) with no backend, or
 * opened while the backend is restarting. Previously every page in that state
 * rendered "Could not load services" and showed the visitor nothing at all —
 * the worst possible outcome for a site meant to help someone in an emergency.
 *
 * What this is and is not:
 *   - It IS real data: the same OpenStreetMap records the database is seeded
 *     from, at their real coordinates.
 *   - It is NOT a substitute for the API. It never marks anything verified,
 *     and the UI states plainly that it is showing saved offline data.
 */

import type { Category, Listing, SearchParams } from './api';
import { town } from '../config/site';

export interface DirectorySnapshot {
  generated_from: string;
  attribution: string;
  town: { name: string; region: string; district: string; lat: number; lng: number };
  categories: Category[];
  listings: Listing[];
}

let cached: Promise<DirectorySnapshot | null> | null = null;

/** Haversine distance in metres, used for radius filtering and sorting. */
function distanceMeters(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const r = 6371000;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * r * Math.asin(Math.min(1, Math.sqrt(a)));
}

/** Loads the snapshot once per page load and caches it. */
export function loadDirectorySnapshot(): Promise<DirectorySnapshot | null> {
  if (cached) return cached;

  cached = fetch(`${import.meta.env.BASE_URL}data/listings.json`)
    .then((res) => {
      if (!res.ok) throw new Error(`snapshot ${res.status}`);
      return res.json() as Promise<DirectorySnapshot>;
    })
    .catch((err) => {
      console.warn('[directory] offline snapshot unavailable:', err);
      return null;
    });

  return cached;
}

export interface SnapshotSearchResult {
  items: Listing[];
  total: number;
  page: number;
  per_page: number;
  total_pages: number;
  /** Distance from the search origin, filled in when lat/lng were supplied. */
  distances: Map<string, number>;
}

/**
 * Client-side equivalent of the backend's `/listings` search, so the offline
 * snapshot behaves like the live API rather than being an unfilterable blob.
 */
export async function searchSnapshot(
  params: SearchParams = {}
): Promise<SnapshotSearchResult> {
  const snapshot = await loadDirectorySnapshot();
  if (!snapshot) {
    return { items: [], total: 0, page: 1, per_page: 20, total_pages: 1, distances: new Map() };
  }

  const { q, category_id, lat, lng, radius, verified_only, sort_by, page = 1, per_page = 20 } = params;
  const needle = q?.trim().toLowerCase();

  let items = [...snapshot.listings];

  if (needle) {
    items = items.filter((l) =>
      [l.name, l.address, l.description, l.category?.name, l.name_local]
        .filter(Boolean)
        .some((field) => String(field).toLowerCase().includes(needle))
    );
  }

  if (category_id) {
    // Accept a numeric id (both sources) or a slug, so a URL like
    // /c/healthcare filters correctly against either.
    const numeric = Number(category_id);
    const slug = String(category_id);
    items = items.filter(
      (l) =>
        (Number.isFinite(numeric) && l.category_id === numeric) ||
        l.category?.slug === slug
    );
  }

  if (verified_only) {
    items = items.filter((l) => l.verified);
  }

  // Radius needs an origin. Fall back to the town centre so the radius
  // selector behaves the same as it does against the live API.
  const originLat = lat ?? town.lat;
  const originLng = lng ?? town.lng;
  const distances = new Map<string, number>();
  for (const l of items) {
    distances.set(l.id, distanceMeters(originLat, originLng, l.lat!, l.lng!));
  }

  if (radius) {
    items = items.filter((l) => (distances.get(l.id) ?? Infinity) <= radius);
  }

  if (sort_by === 'distance') {
    items.sort((a, b) => (distances.get(a.id) ?? 0) - (distances.get(b.id) ?? 0));
  } else if (sort_by === 'name') {
    items.sort((a, b) => a.name.localeCompare(b.name));
  }

  const total = items.length;
  const total_pages = Math.max(1, Math.ceil(total / per_page));
  const start = (Math.max(1, page) - 1) * per_page;
  const paged = items.slice(start, start + per_page);

  // Attach the computed distance so ListingCard can show it as the API does.
  return {
    items: paged.map((l) => ({ ...l, distance_meters: Math.round(distances.get(l.id) ?? 0) })),
    total,
    page,
    per_page,
    total_pages,
    distances,
  };
}

/** Categories from the snapshot, used when `/categories` is unreachable. */
export async function loadSnapshotCategories(): Promise<Category[]> {
  const snapshot = await loadDirectorySnapshot();
  return snapshot?.categories ?? [];
}