/**
 * Generate sitemap.xml and robots.txt from the real route manifest.
 *
 *   npm run generate:sitemap
 *
 * Why this exists
 * ---------------
 * AUDIT.md 5.3: the site shipped no `sitemap.xml` and no `robots.txt`, so search
 * engines had no map of it. Both are derived here from the same route list the
 * app actually renders, plus the category and listing pages that exist in the
 * directory snapshot — so the sitemap cannot advertise a page that 404s.
 *
 * Only public, indexable routes are listed. `/login`, `/register`, `/dashboard`
 * and `/admin` are deliberately excluded: they are per-user, and indexing them
 * wastes crawl budget on pages with no search value.
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const publicDir = resolve(root, 'public');

const cfg = JSON.parse(readFileSync(resolve(root, 'src/config/site.defaults.json'), 'utf8'));
const siteUrl = (process.env.VITE_SITE_URL || cfg.site.url).replace(/\/$/, '');
const today = process.env.SOURCE_DATE_EPOCH
  ? new Date(Number(process.env.SOURCE_DATE_EPOCH) * 1000).toISOString().slice(0, 10)
  : new Date().toISOString().slice(0, 10);

const snapshotPath = resolve(publicDir, 'data/listings.json');
const snapshot = existsSync(snapshotPath)
  ? JSON.parse(readFileSync(snapshotPath, 'utf8'))
  : { categories: [], listings: [] };

/** [path, changefreq, priority] */
const entries = [];

function add(path, changefreq, priority) {
  entries.push({ path, changefreq, priority });
}

add('/', 'daily', 1.0);
add(cfg.routes.emergency, 'weekly', 0.9);
add(cfg.routes.categories, 'weekly', 0.8);
add(cfg.routes.map, 'weekly', 0.6);
add(cfg.routes.about, 'monthly', 0.5);
add(cfg.routes.suggest, 'monthly', 0.6);
add(cfg.routes.report, 'monthly', 0.4);
add(cfg.routes.privacy, 'yearly', 0.3);
add(cfg.routes.accessibility, 'yearly', 0.3);
add(cfg.routes.contact, 'yearly', 0.3);

for (const cat of snapshot.categories ?? []) {
  add(`/c/${cat.slug}`, 'weekly', 0.7);
}

for (const l of snapshot.listings ?? []) {
  add(`/listings/${l.id}`, 'weekly', 0.6);
}

function esc(s) {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

const urls = entries
  .map(
    (e) =>
      `  <url>\n` +
      `    <loc>${esc(`${siteUrl}${e.path === '/' ? '/' : e.path}`)}</loc>\n` +
      `    <lastmod>${today}</lastmod>\n` +
      `    <changefreq>${e.changefreq}</changefreq>\n` +
      `    <priority>${e.priority.toFixed(1)}</priority>\n` +
      `  </url>`
  )
  .join('\n');

const sitemap =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by scripts/generate-sitemap.mjs. Do not edit by hand. -->\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`;

const robots =
  `User-agent: *\n` +
  `Allow: /\n` +
  `\n` +
  `# Per-user routes carry no public search value.\n` +
  `Disallow: /admin\n` +
  `Disallow: /dashboard\n` +
  `Disallow: /login\n` +
  `Disallow: /register\n` +
  `\n` +
  `Sitemap: ${siteUrl}/sitemap.xml\n`;

mkdirSync(publicDir, { recursive: true });
writeFileSync(resolve(publicDir, 'sitemap.xml'), sitemap);
writeFileSync(resolve(publicDir, 'robots.txt'), robots);

console.log(`\n  sitemap.xml: ${entries.length} URLs`);
console.log('  robots.txt written');
console.log(`  origin: ${siteUrl}\n`);