/**
 * Generate Open Graph images at build time.
 *
 *   npm run generate:og
 *
 * ── This script must never fail the build ────────────────────────────────────
 * `sharp` is a native module: it needs a per-platform prebuilt binary
 * (`@img/sharp-linux-x64`, `-linuxmusl-x64`, …) and Node >= 20.9. A build host
 * that lacks the right binary — an older Node on a CI runner, a production-mode
 * install that skipped devDependencies, a platform with no prebuild — cannot
 * render images. Failing the whole deployment over a share preview would be a
 * bad trade, so this script degrades instead:
 *
 *   - `sharp` unavailable  -> warn, skip, exit 0
 *   - no directory snapshot-> warn, skip, exit 0
 *   - one card fails to render -> warn about that card, keep going
 *
 * The homepage card is committed to the repo (`public/og/home.png`) precisely so
 * that a skipped run still leaves a valid `og:image` rather than a 404. See the
 * note in `index.html`.
 *
 * ── What this is for ─────────────────────────────────────────────────────────
 * Every share of a TownPulse link was a bare text URL. The product's whole
 * distribution strategy is "forward this to a neighbour on WhatsApp", and
 * WhatsApp will not render a link card without `og:image`. This script renders
 * one PNG per listing, per category and for the homepage, so each share shows
 * the place name, its category and its verification state.
 *
 * ── Design constraints ───────────────────────────────────────────────────────
 *  - 1200x630 is the size every major consumer expects (1.91:1).
 *  - Colours are read from `src/styles/tokens.css` rather than hardcoded, so
 *    the cards cannot drift from the "Clay & Teak" identity.
 *  - Long place names are word-wrapped and ellipsised so they never overflow.
 *  - Rendered with `sharp` from an SVG source: no headless browser and no
 *    Chromium download in CI.
 *
 * Output goes to `public/og/` (regenerated by the `prebuild` hook, and
 * gitignored — see `.gitignore`) plus a `manifest.json` mapping a route key to
 * its image path, which the runtime `Seo` layer reads.
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const outDir = resolve(root, 'public/og');

/**
 * Reduce the manifest to only the images that genuinely exist on disk.
 *
 * Called when rendering is skipped. Leaving a previously-generated manifest in
 * place is the dangerous option: it still advertises one card per listing and
 * category, so every share would resolve to a PNG that was never written. That
 * is precisely the failure this whole fallback exists to prevent.
 */
function writeMinimalManifest() {
  mkdirSync(outDir, { recursive: true });
  const home = resolve(outDir, 'home.png');
  writeFileSync(
    resolve(outDir, 'manifest.json'),
    `${JSON.stringify(existsSync(home) ? { home: '/og/home.png' } : {}, null, 2)}\n`
  );
}

// ── Optional native dependency ───────────────────────────────────────────────

let sharp = null;
try {
  ({ default: sharp } = await import('sharp'));
} catch (err) {
  // Nothing was rendered, so the only image guaranteed to exist is the
  // committed home card. The manifest MUST be reduced to match reality:
  // `useSeo` reads it to pick an og:image, and `prerender.mjs` writes it into
  // each page's <head>. Leaving a stale manifest claiming 179 cards while only
  // home.png exists points every share at a 404 — the exact failure this
  // fallback exists to prevent.
  writeMinimalManifest();
  console.warn(
    '\n  [generate:og] sharp is unavailable, so share images were not ' +
      `regenerated (${err?.message ?? err}).`
  );
  console.warn(
    '  [generate:og] Continuing. The manifest has been reduced to the ' +
      'committed public/og/home.png, which every page will fall back to.\n'
  );
  process.exit(0);
}

const W = 1200;
const H = 630;

/** Pull `--tp-*` hex values out of the light block of tokens.css. */
function readTokens() {
  const css = readFileSync(resolve(root, 'src/styles/tokens.css'), 'utf8');
  const start = css.indexOf(':root {');
  const end = css.indexOf('\n}', start);
  const vars = {};
  for (const m of css.slice(start, end).matchAll(/--([\w-]+):\s*(#[0-9a-fA-F]{6})\s*;/g)) {
    vars[m[1]] = m[2];
  }
  return vars;
}

const tokens = readTokens();
const T = {
  bg: tokens['bg'] ?? '#fbf7f0',
  text: tokens['text'] ?? '#2b211a',
  muted: tokens['text-muted'] ?? '#6a5a4a',
  primary: tokens['primary'] ?? '#9a3412',
  accent: tokens['accent'] ?? '#14543c',
  warn: tokens['unverified'] ?? '#8a4108',
  warnSoft: tokens['unverified-soft'] ?? '#fbeedb',
};

/** Escape for XML character data. */
function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Font stack for the cards.
 *
 * sharp rasterises SVG with librsvg, which resolves `font-family` against the
 * fonts installed on the *build* machine. `sans-serif` is not reliable: on this
 * Windows image it resolved to a serif face, which would have put a Times-like
 * face on every civic share card. Naming real families in preference order
 * keeps Linux CI (Liberation/DejaVu) and macOS/Windows (Arial/Helvetica) close
 * enough that wrapping behaves the same everywhere.
 */
const FONT = "Arial, 'Liberation Sans', 'Helvetica Neue', Helvetica, 'DejaVu Sans', sans-serif";

/** Glyph widths are calibrated once at these sizes, then scaled linearly. */
const REF_SIZE = 100;

/** Bold glyphs are wider than regular ones, so metrics are kept per weight. */
const WEIGHTS = [400, 700];
const charWidths = {};

/**
 * Correction factor applied to the summed per-glyph ink widths.
 *
 * Measuring a glyph on its own captures its ink bounding box, which excludes
 * the side bearings and the inter-letter advance the renderer actually uses.
 * Summing those ink boxes therefore under-reports a real string by a stable
 * ~18-22%. Measured across four sample strings and five font sizes the ratio
 * stayed within 1.167-1.224, so a single slightly-pessimistic factor absorbs
 * it. Over-estimating is the safe direction: it wraps a line early, whereas
 * under-estimating pushed the homepage title off the right edge of the card.
 */
const INK_TO_ADVANCE = 1.23;

/**
 * Measure the advance width of every printable ASCII glyph by rendering them
 * one per row and scanning the ink. A hardcoded width ratio silently overflowed
 * cards for long place names, so the real metrics are used instead.
 *
 * Calibrating only the regular weight was itself a bug: bold titles measured
 * against regular metrics under-report by ~8%, which pushed the homepage title
 * off the right-hand edge of the card.
 */
async function calibrate(weight) {
  const chars = [];
  for (let c = 32; c <= 126; c += 1) chars.push(String.fromCharCode(c));

  const rowH = 170;
  const width = 420;
  const height = chars.length * rowH;
  const spans = chars
    .map(
      (ch, i) =>
        `<text x="20" y="${i * rowH + 115}" font-family="${FONT}" font-size="${REF_SIZE}" font-weight="${weight}" fill="#ffffff">${esc(ch)}</text>`
    )
    .join('');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="${width}" height="${height}" fill="#000000"/>${spans}</svg>`;

  const { data, info } = await sharp(Buffer.from(svg))
    .greyscale()
    .raw()
    .toBuffer({ resolveWithObject: true });

  const widths = {};
  for (let i = 0; i < chars.length; i += 1) {
    const y0 = i * rowH;
    let min = Infinity;
    let max = -Infinity;
    for (let y = y0; y < y0 + rowH; y += 1) {
      for (let x = 0; x < info.width; x += 1) {
        if (data[y * info.width + x] > 128) {
          if (x < min) min = x;
          if (x > max) max = x;
        }
      }
    }
    // A space has no ink, so fall back to a nominal advance rather than 0.
    widths[chars[i]] = max === -Infinity ? REF_SIZE * 0.3 : max - min + 1;
  }
  return widths;
}

/** Width of `str` at `size` and `weight`, from the calibrated metrics. */
function measure(str, size, weight = 700) {
  const table = charWidths[weight] ?? charWidths[700];
  let total = 0;
  for (const ch of String(str)) total += table[ch] ?? table['?'];
  return (total * INK_TO_ADVANCE * size) / REF_SIZE;
}

/**
 * Greedy word wrap into at most `maxLines`, ellipsising the final line when the
 * text does not fit. Returns the lines actually drawn.
 */
function wrap(str, size, maxWidth, maxLines, weight = 700) {
  const words = String(str ?? '').split(/\s+/).filter(Boolean);
  if (words.length === 0) return [''];

  const lines = [];
  let line = '';
  let truncated = false;

  for (const word of words) {
    if (lines.length === maxLines) {
      truncated = true;
      break;
    }
    const candidate = line ? `${line} ${word}` : word;
    if (measure(candidate, size, weight) <= maxWidth) {
      line = candidate;
    } else {
      if (line) lines.push(line);
      line = word;
    }
  }
  if (!truncated && line) lines.push(line);

  if (lines.length === 0) lines.push('');

  const lastIndex = lines.length - 1;
  if (truncated || measure(lines[lastIndex], size, weight) > maxWidth) {
    let tail = lines[lastIndex];
    while (tail.length > 1 && measure(`${tail}...`, size, weight) > maxWidth) {
      tail = tail.slice(0, -1);
    }
    lines[lastIndex] = `${tail}...`;
  }
  return lines;
}

/**
 * Render a wrapped text block. Returns the SVG plus the vertical distance from
 * the first baseline to the last, so callers can flow content below it instead
 * of guessing fixed offsets.
 */
function textBlock(
  str,
  { x, y, size, fill, maxWidth, maxLines, lineHeight = 1.16, weight = 700, anchor = 'start' }
) {
  const lines = wrap(str, size, maxWidth, maxLines, weight);
  const lh = Math.round(size * lineHeight);
  const spans = lines
    .map(
      (l, i) =>
        `<tspan x="${x}" dy="${i === 0 ? 0 : lh}">${esc(l)}</tspan>`
    )
    .join('');
  return {
    svg: `<text x="${x}" y="${y}" font-family="${FONT}" font-size="${size}" font-weight="${weight}" fill="${fill}" text-anchor="${anchor}">${spans}</text>`,
    height: lh * (lines.length - 1),
    lines: lines.length,
  };
}
/**
 * Shared card frame: warm background, identity bar, town wordmark. Every card
 * uses it so a stream of shares looks like one product.
 */
const FONT_STACK = FONT;

function frame(inner, { eyebrow, badge = '' }) {
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">
  <rect width="${W}" height="${H}" fill="${T.bg}"/>
  <rect x="0" y="0" width="${W}" height="12" fill="${T.primary}"/>
  ${textBlock(eyebrow, { x: 72, y: 108, size: 30, fill: T.primary, maxWidth: W - 144, maxLines: 1, weight: 600 }).svg}
  ${inner}
  ${badge}
  <text x="72" y="${H - 52}" font-family="${FONT_STACK}" font-size="26" font-weight="700" fill="${T.text}">TownPulse</text>
  <text x="${W - 72}" y="${H - 52}" font-family="${FONT_STACK}" font-size="26" text-anchor="end" fill="${T.muted}">townpulse.app</text>
</svg>`;
}

/**
 * Verification chip. Kept honest: an unverified listing says so on the card,
 * because a share implying verification the project has not done is the exact
 * failure the data rebuild set out to fix.
 */
function verifiedBadge(isVerified) {
  if (isVerified) {
    return `<g><rect x="${W - 72 - 236}" y="${H - 148}" width="236" height="58" rx="29" fill="${T.accent}"/>
  <text x="${W - 72 - 118}" y="${H - 109}" font-family="${FONT}" font-size="26" font-weight="700" fill="#ffffff" text-anchor="middle">Verified listing</text></g>`;
  }
  return `<g><rect x="${W - 72 - 268}" y="${H - 148}" width="268" height="58" rx="29" fill="${T.warnSoft}" stroke="${T.warn}" stroke-width="2"/>
  <text x="${W - 72 - 134}" y="${H - 109}" font-family="${FONT}" font-size="26" font-weight="700" fill="${T.warn}" text-anchor="middle">Not yet verified</text></g>`;
}

function homeCard(cfg) {
  // Flow the subtitle off the measured title height so a three-line title can
  // never collide with it.
  const title = textBlock(cfg.title, {
    x: 72,
    y: 250,
    size: 68,
    fill: T.text,
    maxWidth: W - 144,
    maxLines: 3,
  });
  const subtitle = textBlock(cfg.subtitle, {
    x: 72,
    y: 250 + title.height + 96,
    size: 33,
    fill: T.muted,
    maxWidth: W - 144,
    maxLines: 2,
    weight: 400,
  });
  return frame(`${title.svg}${subtitle.svg}`, {
    eyebrow: `${cfg.town}, ${cfg.region}`,
  });
}

function categoryCard(cfg) {
  const title = textBlock(cfg.title, {
    x: 72,
    y: 268,
    size: 62,
    fill: T.text,
    maxWidth: W - 144,
    maxLines: 2,
  });
  const subtitle = textBlock(cfg.subtitle, {
    x: 72,
    y: 268 + title.height + 92,
    size: 33,
    fill: T.muted,
    maxWidth: W - 144,
    maxLines: 2,
    weight: 400,
  });
  return frame(`${title.svg}${subtitle.svg}`, { eyebrow: cfg.eyebrow });
}

function listingCard(cfg) {
  // Reserve the right-hand column for the verification chip so a long name
  // wraps against the chip rather than sliding underneath it.
  const title = textBlock(cfg.name, {
    x: 72,
    y: 252,
    size: 60,
    fill: T.text,
    maxWidth: W - 72 - 300,
    maxLines: 3,
  });

  const ruleY = 252 + title.height + 40;
  const category = textBlock(cfg.category, {
    x: 72,
    y: ruleY + 84,
    size: 32,
    fill: T.primary,
    maxWidth: W - 72 - 300,
    maxLines: 1,
    weight: 600,
  });
  const detail = textBlock(cfg.detail, {
    x: 72,
    y: ruleY + 84 + category.height + 56,
    size: 29,
    fill: T.muted,
    maxWidth: W - 72 - 300,
    maxLines: 1,
    weight: 400,
  });

  return frame(
    `${title.svg}
  <rect x="72" y="${ruleY}" width="96" height="6" rx="3" fill="${T.primary}"/>
  ${category.svg}
  ${detail.svg}`,
    { eyebrow: cfg.eyebrow, badge: verifiedBadge(cfg.verified) }
  );
}

// ── Main ────────────────────────────────────────────────────────────────────

const cfg = JSON.parse(readFileSync(resolve(root, 'src/config/site.defaults.json'), 'utf8'));
const townLabel = `${cfg.town.name}, ${cfg.town.region}`;

const snapshotPath = resolve(root, 'public/data/listings.json');
if (!existsSync(snapshotPath)) {
  // Same reasoning as the missing-sharp branch: no cards will be written, so
  // the manifest must not keep advertising them.
  writeMinimalManifest();
  console.warn(
    '\n  [generate:og] public/data/listings.json is missing — run ' +
      '`npm run sync:directory` first. Skipping image generation.\n'
  );
  process.exit(0);
}
const snapshot = JSON.parse(readFileSync(snapshotPath, 'utf8'));

mkdirSync(outDir, { recursive: true });

// Glyph metrics must be measured before any card is laid out, and bold text
// needs its own table.
for (const weight of WEIGHTS) {
  charWidths[weight] = await calibrate(weight);
}

const jobs = [];
const manifest = {};

/** Queue one card and record its path for the runtime Seo layer. */
function add(name, svg) {
  // `name` is kept alongside `file` so a card that fails to render can be
  // removed from the manifest by key.
  jobs.push({ name, file: `${name}.png`, svg });
  manifest[name] = `/og/${name}.png`;
}

add(
  'home',
  homeCard({
    town: cfg.town.name,
    region: cfg.town.region,
    title: cfg.site.tagline,
    subtitle:
      'Clinics, mechanics, food, shelter and civic offices — with the source and the date checked for every entry.',
  })
);

for (const cat of snapshot.categories ?? []) {
  const count = (snapshot.listings ?? []).filter((l) => l.category_id === cat.id).length;
  add(
    `category-${cat.slug}`,
    categoryCard({
      // Several categories genuinely have no entries in this town's OSM
      // extract (Hampi has no healthcare or mechanics mapped). Saying
      // "0 listings" is honest; implying a count we do not have is not.
      eyebrow:
        count > 0
          ? `${townLabel} · ${count} ${count === 1 ? 'listing' : 'listings'}`
          : `${townLabel} · no listings yet`,
      title: cat.name,
      subtitle: cat.description ?? '',
    })
  );
}

for (const l of snapshot.listings ?? []) {
  // A missing phone number is stated, never invented — the same rule the UI
  // follows, so a share card cannot imply a number we do not have.
  const detail =
    l.phone ||
    (l.address && l.address !== 'Address not listed' ? l.address : 'No phone number listed yet');
  add(
    `listing-${l.id}`,
    listingCard({
      eyebrow: townLabel,
      name: l.name,
      category: l.category?.name ?? 'Local service',
      detail,
      verified: Boolean(l.verified),
    })
  );
}

// A single unrenderable card must not sink the whole build; it is reported and
// skipped. The manifest is filtered to the cards that actually exist, so a
// partial run never points a share at a PNG that was not written.
let done = 0;
const failed = [];

for (const job of jobs) {
  try {
    await sharp(Buffer.from(job.svg))
      .png({ compressionLevel: 9 })
      .toFile(resolve(outDir, job.file));
    done += 1;
  } catch (err) {
    failed.push(`${job.file}: ${err?.message ?? err}`);
    delete manifest[job.name];
  }
}

writeFileSync(resolve(outDir, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);

console.log(`\n  ${done} Open Graph images written to public/og/`);
console.log(`  manifest: public/og/manifest.json (${Object.keys(manifest).length} entries)`);
if (failed.length > 0) {
  console.warn(
    `  ${failed.length} card(s) failed to render and were removed from the ` +
      'manifest, so they fall back to home.png:'
  );
  for (const f of failed.slice(0, 5)) console.warn(`    - ${f}`);
}
console.log('');